dist: trusty
sudo: required

git:
  depth: 1

language: cpp

env:
  matrix:
    - OVERRIDE_PATH=/usr/lib/binutils-2.26/bin

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - binutils-2.26
            - libxkbcommon-x11-dev
            - libudev-dev

script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 100 ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100 ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then chmod +x build_linux.sh ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then TAG_NAME=${TRAVIS_TAG} CXX="g++-6" CC="gcc-6" ./build_linux.sh ; fi

deploy:
  - provider: releases
    api_key:
      secure: "Gyw7v5LLrQqunwMoc/l3zEZCur+wi0bUmODYkumUBuXw+hMi4iV0TWvEtjrjcOObxBUdwiAcl/8S8kOW6GUJCoxP4duNlXN/SZMPepm7ZR13/pPEgTGt3kDuBXcFfKOJHR896UA8tQLTNxjqvyS4g6hNRqC6TCEyT3o1l71f7kGdG8knanEFKsVXTGzVmvoQdtR+FKw0RN7n9DkIiR+/ZQpS+3l64wWv1tV5MyPlvMiTrElKpZPGDWmwkLBYK3lkgshaGcz8Q0niiGdoLTcP/cb1A224TZEa4zfzaXelKwFFa0odBeidmL5HB47Dzox6nTWayy8DvEyzK87eIC6maeVyaLa7IKn4aNdnXEEEU/eCc6u5HUS4ybAWLbso7LkSD9bUkQzaPuVMFa5upt/sFwOZ1BlNchiqGn9hQeKB4DuE8gLZRGbjEYVHv0TBW2zxAjs/RyLFHFkIAVAksWBgn2ehyMeaOTXUVFY2pImIUA0OXaxMzhUKAsnYw/HPR9tiW3uZ/oakWWfzDPRyOjGTcCaEWXEaW4P89pQEW35CXHFfEuu3V1oXUkwezA9SkXPJkBzj3b1BXpUouRmJYvtp7VyO7NIrEpQmp2zFa7k+jPtDv4VSC9r28llVHDcC6UbizFYGi1TXCnQ/rvnEUAcShPoyJbMxAJ4+dWDvY6FYfXk="
    file:
      - build/bin/Csound_${TRAVIS_TAG}_linux_x86_64_Online_installer
    overwrite: true
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux


after_deploy:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then chmod +x push_commit.sh ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then ./push_commit.sh ; fi
