dist: trusty
sudo: required

git:
  depth: 1

language: cpp

env:
  matrix:
    - OVERRIDE_PATH=/usr/lib/binutils-2.26/bin

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - libxkbcommon-x11-dev
            - libudev-dev
            - binutils-2.26

script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 100 ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 100 ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then chmod +x build_linux.sh ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then TAG_NAME=${TRAVIS_TAG} CXX="g++-6" CC="gcc-6" ./build_linux.sh ; fi

deploy:
  - provider: releases
    api_key:
      secure: ALD1tykTfCMb2tkuzjncNqfcllya40GkKfjKnyUaF0VZazoYNbPmeX07QMPjqyqeW2cCYLiVsnYy21/zK2fhfzO2qrVF/7uBJa8LZh4pwXy67RqbMVT8CAJ1oJoXn5ygdjbx4xwI/4CWYHW0pdxQbaSE15ieB4nTVg+heH91rirsZzluM4TApolWS18JyJP8mVct65nYfSrl3I75rZ5JM2+h7Fy82FYqagweBpYZzSXgC2aL4CNWrDDrVR+DAouoxE2CljVJBl5Rs2YD5mWW+XcHm6OVFTuwL9DENBEsTqq+q3JfhPVP9iP0O3k767JV/RAbe28zj/Z8JojBvEPGEszT8djGk5gPz6frobopADDoyZwsFFnH4WiPSgqq0tdD7E7FRO5flhKaLcZy4XMeiUkLHEu4hUjNl/ujG9XnenUF0/QLc/EJsmRgEqO84BWCN/fH8jdfpabkGQVpXkXms5pzf8o7pALX1FyxuhtQEbxeYohZAiIAzQItK/Jpcmz+2hOcd6SNECU/efAhrCMfMMyjgfbzw6D+TmrRn5LOgBJkq4heH4levA2qNv4U2oyQwhoeQpm+T09YkxlXXtNGRgQS7nKE28l3H4jKlrngb1hb3DoDqMFgl+w++2FxAes2KqJw4k47dza7H91YUewXpM7fcAe1pTd3TpMZXPn4pOY=
    file:
      - build/Csound_${TRAVIS_TAG}_linux_x86_64_Online_installer
    overwrite: true
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
